# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/BabyGrChombo_nbdev',
                'doc_host': 'https://GitHimanshuc.github.io',
                'git_url': 'https://github.com/GitHimanshuc/BabyGrChombo_nbdev',
                'lib_path': 'BabyGrChombo_nbdev'},
  'syms': { 'BabyGrChombo_nbdev.core': { 'BabyGrChombo_nbdev.core.foo': ( 'https://GitHimanshuc.github.io/core.html#foo',
                                                                          'https://github.com/GitHimanshuc/BabyGrChombo_nbdev/blob/master/BabyGrChombo_nbdev/core.py#L7')}}}